import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; 
import StoreProvider from "./redux";
import { SidebarProvider } from "@/context/SidebarContext"; 
import { ModalProvider } from "@/context/ModalContext";
import CreateProjectModal from "@/components/Project/CreateProjectModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <AuthProvider>
            <SidebarProvider>
              <ModalProvider>
                {children}
                <CreateProjectModal />
              </ModalProvider>
            </SidebarProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}