# Generated by Django 5.1.7 on 2025-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("project_manager", "Куратор проекта"),
                    ("team_leader", "Лидер подгруппы"),
                    ("team_member", "Участник команды"),
                ],
                default="team_member",
                max_length=50,
            ),
        ),
    ]
