# Generated by Django 5.1.7 on 2025-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_notification_updated_at_project_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("В процессе", "В процессе"),
                    ("Завершено", "Завершено"),
                ],
                default="Новая",
                max_length=50,
            ),
        ),
    ]
