# Generated by Django 5.1.7 on 2025-03-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
    ]
