# Generated by Django 5.1.7 on 2025-04-15 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_assignee_task_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("В процессе", "В процессе"),
                    ("Завершено", "Завершено"),
                ],
                default="Новая",
                max_length=50,
            ),
        ),
    ]
