# Generated by Django 5.1.7 on 2025-04-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_subtask_points_subtask_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtask",
            name="assignee",
        ),
    ]
