# Generated by Django 5.1.7 on 2025-04-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_remove_subtask_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtask_tags",
                to="tasks.tag",
            ),
        ),
    ]
