# Generated by Django 5.1.7 on 2025-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_remove_subtask_assigned_to_subtask_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="priority",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
