# Generated by Django 5.1.7 on 2025-04-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_subtask_description_alter_subtask_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="subtask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tasks.subtask",
            ),
        ),
    ]
