# Generated by Django 5.1.7 on 2025-04-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_alter_comment_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="points",
        ),
    ]
