# Generated by Django 5.1.7 on 2025-04-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_remove_task_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
