# Generated by Django 5.1.7 on 2025-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_team_participants_alter_userteamrelation_role_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userteamrelation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="team",
            name="participants",
        ),
        migrations.AlterField(
            model_name="userteamrelation",
            name="role",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
