# Generated by Django 5.1.7 on 2025-04-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_userprofile_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="productOwnerUserId",
        ),
        migrations.RemoveField(
            model_name="team",
            name="projectManagerUserId",
        ),
        migrations.AddField(
            model_name="team",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
