# Generated by Django 5.1.7 on 2025-04-30 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_remove_project_team_project_curator_project_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgoal",
            name="position_x",
            field=models.FloatField(
                default=0.0, help_text="X координата на стратегической карте"
            ),
        ),
        migrations.AddField(
            model_name="projectgoal",
            name="position_y",
            field=models.FloatField(
                default=0.0, help_text="Y координата на стратегической карте"
            ),
        ),
        migrations.AddField(
            model_name="subgoal",
            name="position_x",
            field=models.FloatField(
                default=0.0, help_text="X координата на стратегической карте"
            ),
        ),
        migrations.AddField(
            model_name="subgoal",
            name="position_y",
            field=models.FloatField(
                default=0.0, help_text="Y координата на стратегической карте"
            ),
        ),
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "position_x",
                    models.FloatField(
                        default=0.0, help_text="X coordinate on strategic map"
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        default=0.0, help_text="Y coordinate on strategic map"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to="tasks.projectgoal",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to="tasks.project",
                    ),
                ),
                (
                    "subgoal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to="tasks.subgoal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategicConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("goal_to_subgoal", "Цель к Подцели"),
                            ("goal_to_task", "Цель к Задаче"),
                            ("subgoal_to_task", "Подцель к Задаче"),
                            ("goal_to_goal", "Цель к Цели"),
                            ("subgoal_to_subgoal", "Подцель к Подцели"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Связь между целями",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="tasks.projectgoal",
                    ),
                ),
                (
                    "source_subgoal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_sub_connections",
                        to="tasks.subgoal",
                    ),
                ),
                (
                    "target_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="tasks.projectgoal",
                    ),
                ),
                (
                    "target_subgoal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_sub_connections",
                        to="tasks.subgoal",
                    ),
                ),
                (
                    "target_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_goals",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("source_goal", "target_goal"),
                    ("source_goal", "target_subgoal"),
                    ("source_goal", "target_task"),
                    ("source_subgoal", "target_goal"),
                    ("source_subgoal", "target_subgoal"),
                    ("source_subgoal", "target_task"),
                },
            },
        ),
        migrations.CreateModel(
            name="UserCursorPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField(default=0.0)),
                ("position_y", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cursors",
                        to="tasks.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursor_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project")},
            },
        ),
    ]
