# Generated by Django 5.1.7 on 2025-04-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_projectgoal_position_x_projectgoal_position_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgoal",
            name="color",
            field=models.CharField(
                default="#FFFFFF", help_text="Цвет узла в формате HEX", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="projectgoal",
            name="progress",
            field=models.FloatField(
                default=0.0, help_text="Прогресс выполнения цели в процентах"
            ),
        ),
        migrations.AddField(
            model_name="subgoal",
            name="color",
            field=models.CharField(
                default="#E0F7FA", help_text="Цвет узла в формате HEX", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="subgoal",
            name="progress",
            field=models.FloatField(
                default=0.0, help_text="Прогресс выполнения подцели в процентах"
            ),
        ),
        migrations.AlterField(
            model_name="projectgoal",
            name="position_x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="projectgoal",
            name="position_y",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="projectgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("В процессе", "В процессе"),
                    ("Завершено", "Завершено"),
                ],
                default="Новая",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subgoal",
            name="position_x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="subgoal",
            name="position_y",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="subgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("В процессе", "В процессе"),
                    ("Завершено", "Завершено"),
                ],
                default="Новая",
                max_length=50,
            ),
        ),
    ]
