# Generated by Django 5.1.7 on 2025-05-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_projectgoal_color_projectgoal_progress_subgoal_color_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="strategicconnection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="strategicconnection",
            name="target_subtask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_subgoals",
                to="tasks.subtask",
            ),
        ),
        migrations.AlterField(
            model_name="strategicconnection",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("goal_to_subgoal", "Цель к Подцели"),
                    ("goal_to_task", "Цель к Задаче"),
                    ("subgoal_to_task", "Подцель к Задаче"),
                    ("goal_to_goal", "Цель к Цели"),
                    ("subgoal_to_subgoal", "Подцель к Подцели"),
                    ("subgoal_to_subtask", "Подцель к Подзадаче"),
                ],
                max_length=50,
            ),
        ),
    ]
