# Generated by Django 5.1.7 on 2025-05-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0028_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_cpd_project",
            field=models.BooleanField(default=False),
        ),
    ]
